version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      day: "sunday"
      time: "12:00"
      timezone: "America/New_York"
